### ISSUE TITLE
How to Accessing method from TRepeater inside TTemplateControl

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#589]
Hello,

i'm stuck, how to accessing method from TRepeater inside TTemplateControl.
MainTemplate.php
```
class MainTemplate extends TTemplateControl {
    public function onLoad ($param) {
		parent::onLoad($param);		        
		if (!$this->Page->IsPostBack&&!$this->Page->IsCallback) {		           
                        $this->populateThemes();
		}        
	}
    public function populateThemes() {
        $themes=$this->Page->setup->getListThemes();
        $daftarthemes=array();
        foreach ($themes as $k=>$v) {
            $daftarthemes[]=array('idtheme'=>$k,'namatheme'=>$v);
        }        
        $this->RepeaterTheme->DataSource=$daftarthemes;
        $this->RepeaterTheme->DataBind();
    }
   public function changeTheme ($sender,$param) {
              $item=$sender->getNamingContainer();
              $themechosen=$this->RepeaterTheme->DataKeys[$item->getItemIndex()];
               echo $themechosen;
    }
}
```
MainTemplate.tpl
```
<!DOCTYPE html>
<html>
<com:THead>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
</com:THead>
<body>
<com:TForm id="mainform">
<div id="loading" style="display: none">
   Please wait while process your request !!!
 </div>
<com:TRepeater ID="RepeaterTheme" DataKeyField="idtheme">
                                <prop:HeaderTemplate>
                                    <ul class="dropdown-menu">
                                </prop:HeaderTemplate>
                                <prop:ItemTemplate>
                                    <li class="item">
                                        <com:TActiveLinkButton ID="btnChangeTheme" ClientSide.PostState="false" OnClick="changeTheme" Enabled="<%#$_SESSION['theme']!=$this->DataItem['idtheme']%>">
                                            <prop:Text>
                                                <%#$_SESSION['theme']==$this->DataItem['idtheme'] ? '<i class="fa fa-check-square"></i>' :''%>
                                                <%#$this->DataItem['namatheme']%>
                                            </prop:Text>
                                            <prop:ClientSide.OnPreDispatch>
                                                $('loading').show();                                             
                                                $('<%=$this->btnChangeTheme->ClientId%>').disabled='disabled';						
                                            </prop:ClientSide.OnPreDispatch>
                                            <prop:ClientSide.OnLoading>
                                                $('<%=$this->btnChangeTheme->ClientId%>').disabled='disabled';									                            
                                            </prop:ClientSide.OnLoading>
                                            <prop:ClientSide.onComplete>
                                                $('loading').hide();                                                
                                            </prop:ClientSide.OnComplete>
                                        </com:TActiveLinkButton>                                        
                                    </li>
                                </prop:ItemTemplate>
                                <prop:FooterTemplate>
                                    </ul>
                                </prop:FooterTemplate>
                            </com:TRepeater>
</com:TForm>
</body>
</html>
```

**Comment by ctrlaltca** [comment]
What's the question?

**Comment by mrizkir** [comment]
My question is why i'm getting error like this :
```
Callback Server Error 500: 
TInvalidDataValueException with message "Component event 'TActiveLinkButton.onclick' is attached with an invalid event handler 'TemplateControl.changeTheme'." in /home/rizki/public_html/framework_323/TComponent.php(1182)
Stack trace:
  #0 /home/rizki/public_html/framework_323/Web/UI/WebControls/TLinkButton.php(318): TComponent->raiseEvent()
  #1 /home/rizki/public_html/framework_323/Web/UI/WebControls/TLinkButton.php(305): TLinkButton->onClick()
  #2 /home/rizki/public_html/framework_323/Web/UI/ActiveControls/TActiveLinkButton.php(77): TLinkButton->raisePostBackEvent()
  #3 /home/rizki/public_html/framework_323/Web/UI/ActiveControls/TActivePageAdapter.php(259): TActiveLinkButton->raiseCallbackEvent()
  #4 /home/rizki/public_html/framework_323/Web/UI/ActiveControls/TActivePageAdapter.php(109): TActivePageAdapter->raiseCallbackEvent()
  #5 /home/rizki/public_html/framework_323/pradolite.php(7492): TActivePageAdapter->processCallbackEvent()
  #6 /home/rizki/public_html/framework_323/pradolite.php(7417): TPage->processCallbackRequest()
  #7 /home/rizki/public_html/framework_323/pradolite.php(9620): TPage->run()
  #8 /home/rizki/public_html/framework_323/pradolite.php(9586): TPageService->runPage()
  #9 /home/rizki/public_html/framework_323/pradolite.php(10767): TPageService->run()
  #10 /home/rizki/public_html/framework_323/pradolite.php(10298): TApplication->runService()
  #11 /home/rizki/public_html/newstisipolrh/index.php(6): TApplication->run()
```

**Comment by ctrlaltca** [comment]
Ok, now i get the problem :)

So, you have a button inside an item template:
```html
<prop:ItemTemplate>
...
  <com:TActiveLinkButton ID="btnChangeTheme" OnClick="changeTheme" ...>
```

That s trying to call a php method inside the page class:
```php
class MainTemplate extends TTemplateControl {
...
   public function changeTheme ($sender,$param) {
```

This doesn't work because the button is defined in the context of the `ItemTemplate`, so it's looking for a method named `changeTheme` inside that context, while the method is defined in the context of the page class.
You can try these to have the button point to the correct method:
```html
<-- Look for the method in the page context --> 
OnClick="Page.changeTheme"
<-- Look for the method in the context of the source file where the control is defined -->
OnClick="SourceTemplateControl.changeTheme"
<-- Ugly: browse the control hierarchy up until you point to the correct one -->
OnClick="Parent.Parent.Parent....changeTheme"
```

**Comment by mrizkir** [comment]
it's working now. Thank you very much.

`OnClick="SourceTemplateControl.changeTheme"
`
