### ISSUE TITLE
fatal error exception

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#673]
I suddently see that error in server log. It happen when user try to authenticate. The result is white page

```
[23-Jun-2018 16:07:11 Africa/Douala] exception 'TPhpErrorException' with message '[Core Warning] Module 'mysql' already loaded (@line 0 in file Unknown).' in /home/camercer/public_html/framework/PradoBase.php:156
Stack trace:
#0 [internal function]: PradoBase::phpFatalErrorHandler()
#1 {main}
[23-Jun-2018 16:07:11 Africa/Douala] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to alter response as HTTP header already sent' in /home/camercer/public_html/framework/Web/THttpResponse.php:280
Stack trace:
#0 /home/camercer/public_html/framework/Exceptions/TErrorHandler.php(202): THttpResponse->setStatusCode(500, NULL)
#1 /home/camercer/public_html/framework/Exceptions/TErrorHandler.php(136): TErrorHandler->handleExternalError(500, Object(TPhpErrorException))
#2 /home/camercer/public_html/framework/PradoBase.php(173): TErrorHandler->handleError(NULL, Object(TPhpErrorException))
#3 /home/camercer/public_html/framework/PradoBase.php(156): PradoBase::exceptionHandler(Object(TPhpErrorException))
#4 [internal function]: PradoBase::phpFatalErrorHandler()
#5 {main}
  thrown in /home/camercer/public_html/framework/Web/THttpResponse.php on line 280
```

prado 3.3.3
php 5.6.36

EDIT
What is 'mysql Module'? I don't have it in my config.

**Comment by ctrlaltca** [comment]
That's a php warning. You are probably including the php's mysql extension more than one in `php.ini` or one of the other included php configs:
```
;extension=mysql.so
```

**Comment by frkinta** [comment]
thanks
