### ISSUE TITLE
friendly setConfigFile

### ISSUE THREAD

**Issue by Airakath** [pradosoft/prado#682]
Hello
I want to use Config File to externalize the configuration of my rewritings into another xml file that I could generate.

I find it hard to understand how to use it correctly.

I always have the error:

Description
urlmapping_configfile_inexistent

```
Fichier Source
/home/nicolas/www-dev/lapetitedistrib/protected/vendor/pradosoft/prado/framework/Web/TUrlMapping.php (144)

0133:     {
0134:         if (is_file($this->_configFile)) {
0135:             if ($this->getApplication()->getConfigurationType() == TApplication::CONFIG_TYPE_PHP) {
0136:                 $config = include $this->_configFile;
0137:                 $this->loadUrlMappings($dom);
0138:             } else {
0139:                 $dom = new TXmlDocument;
0140:                 $dom->loadFromFile($this->_configFile);
0141:                 $this->loadUrlMappings($dom);
0142:             }
0143:         } else {
0144:             throw new TConfigurationException('urlmapping_configfile_inexistent', $this->_configFile);
0145:         }
0146:     }
0147: 
0148:     /**
0149:      * Returns a value indicating whether to enable custom constructUrl.
0150:      * If true, constructUrl() will make use of the URL mapping rules to
0151:      * construct valid URLs.
0152:      * @return bool whether to enable custom constructUrl. Defaults to false.
0153:      * @since 3.1.1
0154:      */
0155:     public function getEnableCustomUrl()
0156:     {

Trace de la pile d'exécution:
#0 /home/nicolas/www-dev/lapetitedistrib/protected/vendor/pradosoft/prado/framework/Web/TUrlMapping.php(114): Prado\Web\TUrlMapping->loadConfigFile()
#1 /home/nicolas/www-dev/lapetitedistrib/protected/vendor/pradosoft/prado/framework/TApplication.php(998): Prado\Web\TUrlMapping->init(Object(Prado\Xml\TXmlElement))
#2 /home/nicolas/www-dev/lapetitedistrib/protected/vendor/pradosoft/prado/framework/TApplication.php(1045): Prado\TApplication->applyConfiguration(Object(Prado\TApplicationConfiguration), false)
#3 /home/nicolas/www-dev/lapetitedistrib/protected/vendor/pradosoft/prado/framework/TApplication.php(369): Prado\TApplication->initApplication()
#4 /home/nicolas/www-dev/lapetitedistrib/index.php(75): Prado\TApplication->run()
#5 {main}
```

Here is my configuration

aplication.xml

       
```
 <paths>
        <!-- <alias id="myalias" path="./lib" /> -->
        <using namespace="Application.Common.*" />
        <using namespace="Application.Database.*"/>
        <using namespace="Application.Database.Custom.*"/>         
        <using namespace="System.Web.UI.*"/>
        <using namespace="System.Web.UI.ActiveControls.*"/>
        <using namespace="System.Web.UI.WebControls.*"/>
        <using namespace="System.Util.*"/>
        <using namespace="System.I18N.*"/>
        <using namespace="System.Security.*"/>
        <using namespace="System.Web.*"/>
        <using namespace="System.Web.UI.JuiControls.*"/>        
        <using namespace="Application.Router.*" /> 
            
    </paths>


     <module id="request" class="THttpRequest" UrlFormat="HiddenPath" UrlManager="friendly-url" EnableCookieValidation="true"/>
        <module id="friendly-url" class="System.Web.TUrlMapping" EnableCustomUrl="true" ConfigFile="Application.Router.*">
       
 
        </module>

```
protected/Router/urlmap.xml

```
<?xml version="1.0" encoding="utf-8"?>

    <url ServiceParameter="Frontend.LandingPage.LandingPage" pattern="LandingPage" />    
    <url ServiceParameter="Frontend.Accueil.Accueil" pattern="" />


```

thank you in advance

**Comment by Airakath** [comment]
I documented myself from
http://pradosoft.github.io/docs/manual/class-Prado.Web.TUrlMapping
and 
http://pradoframework.net/demos/quickstart/index.php?page=Configurations.UrlMapping#

**Comment by ctrlaltca** [comment]
`ConfigFile` must point to a file, so in your case the correct value should be:
```xml
<module id="friendly-url" class="System.Web.TUrlMapping" EnableCustomUrl="true" ConfigFile="Application.Router.urlmap">
```
(The xml extension is added automatically).

Another thing, IIRC the urlmap.xml file needs to have a root elements, eg:
```xml
<?xml version="1.0" encoding="utf-8"?>
<urls>
    <url ServiceParameter="Frontend.LandingPage.LandingPage" pattern="LandingPage" />    
    <url ServiceParameter="Frontend.Accueil.Accueil" pattern="" />
</urls>
```

**Comment by Airakath** [comment]
thank you for your quick response and explanations!

it works !
