### ISSUE TITLE
[Warning] implode(): Invalid arguments passed (@line 48 in file /usr/share/baculum/htdocs/protected/Web/Pages/ClientView.php).

### ISSUE THREAD

**Issue by infomatico** [pradosoft/prado#691]
Hello,

I installed the baculum webGui for bacula backup, but when I click in the "details" about an client, the error below occours:

```
Prado\Exceptions\TPhpErrorException
Description
[Warning] implode(): Invalid arguments passed (@line 48 in file /usr/share/baculum/htdocs/protected/Web/Pages/ClientView.php).

Source File
/usr/share/baculum/htdocs/protected/Web/Pages/ClientView.php (48)

0037:         $clientid = 0;
0038:         if ($this->Request->contains('clientid')) {
0039:             $clientid = $this->Request['clientid'];
0040:         }
0041:         $this->setClientId($clientid);
0042:         $clientshow = $this->getModule('api')->get(
0043:             array('clients', $clientid, 'show'),
0044:             null,
0045:             true
0046:         );
0047:         if ($clientshow->error === 0) {
0048:             $this->ClientLog->Text = implode(PHP_EOL, $clientshow->output);
0049:         }
0050:         $client = $this->getModule('api')->get(
0051:             array('clients', $clientid)
0052:         );
0053:         if ($client->error === 0) {
0054:             $this->setClientName($client->output->name);
0055:             if (!empty($_SESSION['dir'])) {
0056:                 $this->ClientConfig->setComponentName($_SESSION['dir']);
0057:                 $this->ClientConfig->setResourceName($this->getClientName());
0058:                 $this->ClientConfig->setLoadValues(true);
0059:                 $this->ClientConfig->raiseEvent('OnDirectiveListLoad', $this, null);
0060:             }

Stack Trace
#0 [internal function]: Prado\PradoBase::phpErrorHandler(2, 'implode(): Inva...', '/usr/share/bacu...', 48, Array)
#1 /usr/share/baculum/htdocs/protected/Web/Pages/ClientView.php(48): implode('\n', 'show client="ba...')
#2 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TControl.php(1318): ClientView->onInit(NULL)
#3 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TCompositeControl.php(35): Prado\Web\UI\TControl->initRecursive(Object(ClientView))
#4 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TTemplateControl.php(244): Prado\Web\UI\TCompositeControl->initRecursive(NULL)
#5 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TPage.php(220): Prado\Web\UI\TTemplateControl->initRecursive()
#6 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TPage.php(208): Prado\Web\UI\TPage->processNormalRequest(Object(Prado\Web\UI\THtmlWriter))
#7 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/Services/TPageService.php(528): Prado\Web\UI\TPage->run(Object(Prado\Web\UI\THtmlWriter))
#8 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/Services/TPageService.php(465): Prado\Web\Services\TPageService->runPage(Object(ClientView), Array)
#9 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/TApplication.php(1190): Prado\Web\Services\TPageService->run()
#10 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/TApplication.php(382): Prado\TApplication->runService()
#11 /usr/share/baculum/htdocs/index.php(31): Prado\TApplication->run()
#12 {main}
```
Any idea about this error?

**Comment by ctrlaltca** [comment]
Loos like an error in baculum code; old php versions would probably treat the string as an array and somewhat workaround the problem. You are probably running a recent php version configured to treat warning as errors. Maybe @ganiuszka can help?

**Comment by ganiuszka** [comment]
Hello informatico and ctrlaltca,

Thank you for notifying me about this problem.

Yes, ctrlaltca is right that it is Baculum specific problem.

I propose to enable Baculum Web logs (under gearwheel icon on the top left) and on path:

/usr/share/baculum/htdocs/protected/Web/Logs/baculum-web.log

check what exactly output returns Baculum API for Bconsole show client request. There should be an unexpected error. Thank you in advance for showing me this output.

For future problems with Baculum do not hesitate to open Mantis ticket in Bacula bug tracker here:

http://bugs.bacula.org

Thanks for your help.

Best regards.
Marcin Haba (gani)

**Comment by infomatico** [comment]
Thanks @ctrlaltca and @ganiuszka for the help!!

@ganiuszka I created the ticket in bug tracker.
