### ISSUE TITLE
application.xml - Class Prado\Caching\Memcache not found

### ISSUE THREAD

**Issue by szroman** [pradosoft/prado#699]
Hi, me again, thanks for your help and quick response.

Example from **Welcome to PRADO** basic application.

```
Error
Description
Class 'Prado\Caching\Memcache' not found

Source File
${PradoFramework}/Caching/TMemCache.php (162)

0151:      * @throws TConfigurationException if memcache extension is not installed or memcache sever connection fails
0152:      */
0153:     public function init($config)
0154:     {
0155:         if (!extension_loaded('memcache') && !$this->_useMemcached) {
0156:             throw new TConfigurationException('memcache_extension_required');
0157:         }
0158:         if (!extension_loaded('memcached') && $this->_useMemcached) {
0159:             throw new TConfigurationException('memcached_extension_required');
0160:         }
0161: 
0162:         $this->_cache = $this->_useMemcached ? new Memcached : new Memcache;
0163:         $this->loadConfig($config);
0164:         if (count($this->_servers)) {
0165:             foreach ($this->_servers as $server) {
0166:                 Prado::trace('Adding server ' . $server['Host'] . ' from serverlist', '\Prado\Caching\TMemCache');
0167:                 if ($this->_cache->addServer(
0168:                     $server['Host'],
0169:                     $server['Port'],
0170:                     $server['Persistent'],
0171:                     $server['Weight'],
0172:                     $server['Timeout'],
0173:                     $server['RetryInterval']
0174:                 ) === false) {

Stack Trace
#0 ${PradoFramework}/TApplication.php(998): Prado\Caching\TMemCache->init(Object(Prado\Xml\TXmlElement))
#1 ${PradoFramework}/TApplication.php(1045): Prado\TApplication->applyConfiguration(Object(Prado\TApplicationConfiguration), false)
#2 ${PradoFramework}/TApplication.php(369): Prado\TApplication->initApplication()
#3 /home/roman/netcrm/memcachedtest/index.php(18): Prado\TApplication->run()
#4 {main}
2019-08-08 11:56 Apache/2.4.25 (Debian) PRADO/4.0.2
```

application.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>

<application id="memcachedtest" mode="Debug">
  <modules>
    <module id="cache" class="System.Caching.TMemCache" Host="localhost" Port="11211" />
  </modules>
  <services>
    <service id="page" class="TPageService" DefaultPage="Home" />
  </services>
</application>
```

Home.page:
```html
<html>
<head>
  <title>Welcome to PRADO</title>
</head>
<body>
<h1>Welcome to PRADO!</h1>
</body>
</html>
```

composer.json:
```json
{
	"name": "pradosoft/prado-app",
	"type": "project",
	"description": "Prado 4 basic application project",
	"license" : "proprietary",
	"authors": [
		{
			"name": "Author Name",
			"email": "author@email.com",
			"role" : "Developer"
		}
	],
	"repositories": [
		{
			"type": "composer",
			"url": "https://asset-packagist.org"
		}
	],
	"require": {
		"pradosoft/prado": "4.0.2"
	},
	"config": {
		"vendor-dir": "protected/vendor"
	},
	"scripts": {
		"post-install-cmd": [
			"chmod 777 assets",
			"chmod 777 protected/runtime",
			"chmod 777 protected/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer"
		],
		"post-update-cmd": [
			"chmod 777 assets",
			"chmod 777 protected/runtime",
			"chmod 777 protected/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer"
		]
	}
}
```

php7.2-memcache and php7.2-memcached installed

**Comment by ctrlaltca** [comment]
Yep, this has been already fixed in current master.
Line 162 of `Caching/TMemCache.php`:
```
- $this->_cache = $this->_useMemcached ? new Memcached : new Memcache;
+ $this->_cache = $this->_useMemcached ? new \Memcached : new \Memcache;
```

Probably we should backport the fix to 4.0 and tag a new version

**Comment by szroman** [comment]
Don't do it for me, only if other users need it. With 4.1 version I will change from TDbCache to TMemCache. Thanks for help.

**Comment by ctrlaltca** [comment]
Closing.
