### ISSUE TITLE
Proper way of generating application.xml on php

### ISSUE THREAD

**Issue by sicutdeux** [pradosoft/prado#712]
Hi, i'm having trouble translating the application.xml into an php, since v3.2 it should be possible to use, my idea behind this is to use a .php for configs in order to automate deployments using environment vars for db connection strings.

If you have a better suited way to do it let me know, here is the issue:

XML Way:

```
<?xml version="1.0" encoding="utf-8"?>

<application id="prado-app" mode="Debug">
	<paths>
		<using namespace="Application.Common.*" />
	</paths>
	<!-- modules configured and loaded for all services -->
	<modules>
		<module id="request" class="THttpRequest" UrlFormat="HiddenPath" />
		<module id="parameter" class="TParameterModule" ParameterFile="Application.Data.Settings" />
	</modules>
	<services>
		<!-- page service -->
		<service id="page" class="TPageService" DefaultPage="Home">
			<modules>
				<module id="session" class="THttpSession" SessionName="SSID" CookieMode="Only" UseCustomStorage="false" AutoStart="true" TimeOut="28800" />
				<module id="asset" class="System.Web.TAssetManager" />
			</modules>
			<pages MasterClass="Application.Layouts.MainLayout" />
		</service>
	</services>
</application>
```

Php Version:

```
<?php
return array(
  'application' => array(
   'id'=>'prado-app','mode'=>'Debug' 
  ),

  // paths
  'paths'=>array(
    'using'=>array('namespace' => 'Application.Common.*')
  ),
  //modules
  'modules' => array (
    'module'=>array('id'=>'request', 'class'=>'THttpRequest','UrlFormat'=>'HiddenPath'),
    'module'=>array('id'=>'parameter', 'class'=>'TParameterModule','ParameterFile'=>
      'Application.Data.Settings'),
  ),

  //services
  'services'=> array(
    'service'=>array('id'=>'page','class'=>'TPageService','DefaultPage'=>'Home',
      'modules'=>array(
        'module'=>array(
          'id'=>'session','class'=>'THttpSession','SessionName'=>'SSID','CookieMode'=>'Only','UseCustomStorage'=>'false','AutoStart'=>'true','TimeOut'=>'28800'),
        'module'=>array(
          'id'=>'asset','class'=>'System.Web.TAssetManager')
        ),
      'pages'=>array('MasterClass' =>'Application.Layouts.MainLayout')
      ),
  ),
);

```
I Think the problem is at this line:

`      'pages'=>array('MasterClass' =>'Application.Layouts.MainLayout')
`
The error is the following:

```
Prado\Exceptions\TConfigurationException
Description
Control 'Home' requires a master control since the control uses TContent.

Source File
${PradoFramework}/Web/UI/TTemplateControl.php (241)

0230:             if (!($master instanceof TTemplateControl)) {
0231:                 throw new TInvalidDataValueException('templatecontrol_mastercontrol_invalid');
0232:             }
0233:             $this->_master = $master;
0234:             $this->getControls()->clear();
0235:             $this->getControls()->add($master);
0236:             $master->ensureChildControls();
0237:             foreach ($this->_contents as $id => $content) {
0238:                 $master->injectContent($id, $content);
0239:             }
0240:         } elseif (!empty($this->_contents)) {
0241:             throw new TConfigurationException('templatecontrol_mastercontrol_required', get_class($this));
0242:         }
0243:         parent::initRecursive($namingContainer);
0244:     }
0245: 
0246:     /**
0247:      * Function to update view controls with data in a given AR object.
0248:      * View controls and AR object need to have the same name in IDs and Attrs respectively.
0249:      * @param TActiveRecord $arObj
0250:      * @param Boolean $throwExceptions Wheter or not to throw exceptions
0251:      * @author Daniel Sampedro <darthdaniel85@gmail.com>
0252:      */
0253:     public function tryToUpdateView($arObj, $throwExceptions = false)

Stack Trace
#0 ${PradoFramework}/Web/UI/TPage.php(221): Prado\Web\UI\TTemplateControl->initRecursive()
#1 ${PradoFramework}/Web/UI/TPage.php(209): Prado\Web\UI\TPage->processNormalRequest(Object(Prado\Web\UI\THtmlWriter))
#2 ${PradoFramework}/Web/Services/TPageService.php(527): Prado\Web\UI\TPage->run(Object(Prado\Web\UI\THtmlWriter))
#3 ${PradoFramework}/Web/Services/TPageService.php(464): Prado\Web\Services\TPageService->runPage(Object(Home), Array)
#4 ${PradoFramework}/TApplication.php(1189): Prado\Web\Services\TPageService->run()
#5 ${PradoFramework}/TApplication.php(381): Prado\TApplication->runService()
#6 ${DocumentRoot}/daptrius/prado-app/index.php(24): Prado\TApplication->run()
#7 {main}
2020-04-09 02:55 Apache/2.4.43 (Unix) OpenSSL/1.1.1f PHP/7.3.16 PRADO/4.1.1
```
Any thougs of what i'm not doing right?

Thanks.

**Comment by ctrlaltca** [comment]
The blog demo uses a MainLayout and has a working application.php: https://github.com/pradosoft/prado-demos/blob/master/blog/protected/application.php

```
'pages' => array(
	'properties' => array(
		'MasterClass' => 'Application.Layouts.MainLayout',
		'Theme' => 'Basic',
	),
),
```

Please note that in normal and performace mode the application.xml/php is cached, so it probably won't detect changes in the environment variables unless you [touch](https://en.wikipedia.org/wiki/Touch_(command)) the file

**Comment by sicutdeux** [comment]
Fixed, thanks.
