### ISSUE TITLE
_wakeup tries to re-instance TPermissionsManager

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#953]
I finally got my instance up and running and am getting this error.  I'm looking into it.

#0 ${PradoFramework}/Security/Permissions/TPermissionsBehavior.php(112): Prado\Security\Permissions\TPermissionsManager->registerPermission('permissions_she...', 'Activates permi...', Array)
#1 ${PradoFramework}/TComponent.php(1937): Prado\Security\Permissions\TPermissionsBehavior->attach(Object(Prado\Security\Permissions\TPermissionsManager))
#2 ${PradoFramework}/TComponent.php(509): Prado\TComponent->attachBehavior('permissions', Object(Prado\Security\Permissions\TPermissionsBehavior), -10)
#3 [internal function]: Prado\TComponent->__wakeup()
#4 ${PradoFramework}/Caching/TDbCache.php(480): unserialize('a:2:{i:0;a:2:{i...')
#5 ${PradoFramework}/Caching/TCache.php(126): Prado\Caching\TDbCache->getValue('f65a20d7649bba6...')
#6 ${PradoFramework}/Web/Services/TPageService.php(238): Prado\Caching\TCache->get('prado:pageservi...')
#7 ${PradoFramework}/Web/Services/TPageService.php(150): Prado\Web\Services\TPageService->loadPageConfig(Object(Prado\Xml\TXmlElement))
#8 ${PradoFramework}/TApplication.php(1200): Prado\Web\Services\TPageService->init(Object(Prado\Xml\TXmlElement))
#9 ${PradoFramework}/TApplication.php(1161): Prado\TApplication->startService('page')
#10 ${PradoFramework}/TApplication.php(384): Prado\TApplication->initApplication()
#11 /Users/User/Code/2022prado/index.php(24): Prado\TApplication->run()
#12 {main}

**Comment by belisoful** [comment]
This was a bug from working on the TDBCache SQL.  interesting.
